name: dev
channels:
  - conda-forge
dependencies:
  - benchmark=1.9.4
  - binutils=2.45
  - boost-cpp=1.85.0
  - brotli=1.1.0
  - clang-format=21.1.0
  - clang-tools=21.1.0
  - clangxx=21.1.0
  - cmake=4.2.1
  - gcc=15.1.0
  - gmock=1.17.0
  - gtest=1.17.0
  - gxx=15.1.0
  - lcov=1.16
  - libsodium=1.0.20
  - quill=11.0.2
  - zlib=1.3.1
